### ISSUE TITLE
Load timing issue causes a harmless console error in Safari9.

### ISSUE THREAD

**Issue by ppeyro** [PredixDev/px-sass-doc#6]
When viewing certain component pages causes Safari9 to throw a harmless console error that has no visual/functional side effects and can be ignored.    It is a timing issue around loading a svg that eventually does get loaded.
Adding this known issue as a low priority item in this repo.

## Steps to reproduce the problem:
view px-list-bare-design sassdoc.

## Environment:
Safari9 only.

## Screenshot:
![safari_9_warning](https://cloud.githubusercontent.com/assets/10835611/25759706/707ef8fc-3188-11e7-826b-1d8593da72db.png)

**Comment by randyaskin** [comment]
With release of Safari 11 last month, we only need to support Safari 10 & 11.
