### ISSUE TITLE
Mobile: Sass & html code snippets missing in mobile view.

### ISSUE THREAD

**Issue by ppeyro** [PredixDev/px-sass-doc#9]
All demo pages should be complete with their code snippets intact on mobile, but that is not the case in mobile view for at least 2 demo pages: Typography-design and toggle-design.

## Environment:

Iphone6 plus+ios10.3

## Screenshots:

![sass_import_mobile](https://cloud.githubusercontent.com/assets/10835611/25975831/89a59124-3665-11e7-98d1-50e9b3772edb.PNG)

![sass-html-mobile](https://cloud.githubusercontent.com/assets/10835611/25975865/b9846c9e-3665-11e7-85d1-dd0a098601bb.png)

**Comment by randyaskin** [comment]
This seems to have been fixed at some point.
